language: node_js
sudo: true

node_js:
  - '5.6.0'

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6

branches:
  only:
  - master

env:
  global:
  - LOGS_DIR=/tmp/angular-material2-build/logs
  - SAUCE_USERNAME=tinayuangao
  - ARCH=linux-x64
  - BROWSER_PROVIDER_READY_FILE=/tmp/angular-material2-build/readyfile
  matrix:
    # Order: a slower build first, so that we don't occupy an idle travis worker waiting for others to complete.
    - MODE=e2e
    #- secure: "funKN05yYxLgZNCHX+rduZ4jUcNjLXmHejfNFEKkoxrc1JXC0DIupaz8X/7IUUBxFbJsqQVI7T812jWgI4+003s8hxcgy263Fs/ieh3VLWRCYAkyMautkUyidm+1ZDJWhEPU/7heCQxFKs8AY40tN+oYfb7qor+pceCKqrZ0wiXML+gJ/NrOogaJCydPC79jRJojlVOfqNc+V2caZBtzvwkR85tZO3UQGAhoeHpa9JB2Z2hrMSaTIIphuw4wR9FAR79HtSc6OOkEFGJ0n41Tw1JfnRKdZ6n/QRcYs0NI1mELA6GNNtB2Xp2LNw+8B8xXELKkIIxkZmmMEAbM+EniWwNPljuIaMBmiIPlD3/Ig7sf/BRnUs6/cTNMStal2WnG9h7xhziFWv2jEBh6TJF+uAQ1/BGL4ByxI37iJSwk4Ph32/YnefcY+Ppx/JqoWqGnt8YUMce1ZqlSOrDfP+U5XJTBfRdonUOig8OGVcZFFnNC0ch8mVV5aYoYGkW5UIxYV3ZP38vmR7Vzw0j7H7+eOenpUkopGh74sH0k18M/FIpWdaTFjQgCYFnbR4APol2VQ8YhSLX09s/F0E9w6wNt747KEVQonQF8/pjqmCKfPrvqqH5Xiq1SuCk6O/URzxJ6eKc1Vo2mmQh8fpTTXhnC8VUjSWPilscGEGty1b2ghYk="
addons:
  jwt:
    material: 
      - secure: "hpaET0kTokMjZrhTYEmYjFB7xrJmpZygZGOGhK5mGQJK+P08C7YZ/320jZqS6W3E55U/e2IQgJZaJM1VLwCLsC5z03/WKGxFfQve/Iv0TZ9yVkFmynOL2tBfj40EZ+zlXY4lKqixBFN6/g+YP3dMpecV7dlOasuXoGS2KhEtPbYh4c+wxXP4jsqDfMTZ4KtndjSJpefiwB8uf+Yh7ezZGor1unDMBgKq8TtWhn/usS+k75CR/8KrByypMhSGnlbhJ7yNvc7+wJk2AOO/KNp8DPf9M5X36CD+MC+Muww4J9IgxJw1Td1qGgNlxpo5zAtB1FrJQOY0omUJ64P1XRILJdr4JQzurflPTFQU5R4QmoINWZF5lyZ+V1tQycgqLinw+TqBg1Z0m+TxFOZW8Pozr4Pl0/Vv7enB90G4yA6aJ+N1rIiSbg/Ugtdm3uOpqUc/yB6BPUfBXpX4X6oVTE64vUUtUh8cdeZo0s3aOyWJ4S0MkTLBTPTq2Oe7alQqr+gPBu0jzZpi++UYvpR54I3i3Fqt5180ilcH9Xk3FhLGC2ErIxlsCrS5Cq+LBhxMDdc90V8LqVooFXQK/khk2lYd9nnyyQhbUfWQqMMrlIdy5ETcUKb8yHgIK+PRuDKjrXuiocKJuAlW6kl2CgOz0bl0lTwHV3hKEMV3+L7rnT+zJWs="
      - secure: "funKN05yYxLgZNCHX+rduZ4jUcNjLXmHejfNFEKkoxrc1JXC0DIupaz8X/7IUUBxFbJsqQVI7T812jWgI4+003s8hxcgy263Fs/ieh3VLWRCYAkyMautkUyidm+1ZDJWhEPU/7heCQxFKs8AY40tN+oYfb7qor+pceCKqrZ0wiXML+gJ/NrOogaJCydPC79jRJojlVOfqNc+V2caZBtzvwkR85tZO3UQGAhoeHpa9JB2Z2hrMSaTIIphuw4wR9FAR79HtSc6OOkEFGJ0n41Tw1JfnRKdZ6n/QRcYs0NI1mELA6GNNtB2Xp2LNw+8B8xXELKkIIxkZmmMEAbM+EniWwNPljuIaMBmiIPlD3/Ig7sf/BRnUs6/cTNMStal2WnG9h7xhziFWv2jEBh6TJF+uAQ1/BGL4ByxI37iJSwk4Ph32/YnefcY+Ppx/JqoWqGnt8YUMce1ZqlSOrDfP+U5XJTBfRdonUOig8OGVcZFFnNC0ch8mVV5aYoYGkW5UIxYV3ZP38vmR7Vzw0j7H7+eOenpUkopGh74sH0k18M/FIpWdaTFjQgCYFnbR4APol2VQ8YhSLX09s/F0E9w6wNt747KEVQonQF8/pjqmCKfPrvqqH5Xiq1SuCk6O/URzxJ6eKc1Vo2mmQh8fpTTXhnC8VUjSWPilscGEGty1b2ghYk="
      - secure: "Sv4NhtrvGddaVRbI51lAm/Vg4uoUyLuGDKX8XvmFsZPXlGH7z4DfW8jm4XAkNub4FkkwlPkyN0YhbLENEmvUxDznDgl/xWmy9kOIr9hkFB6tvit/FJsQct4G9LGk9voXXOYc3J5id+kt6NGrjHaWzws6/rZRveVm/WsHpu951B78XdIMVr1cP3ChYIRKd/ItwiBb9JmlgyPWSO92LfhjxF10cS6xYQQTle4zXUOAIIcP2/0kifZEqvseonnK8uvfA/TNXDkSM747PqJUiKeRTOlEnW8aix+MErFdDDaddPjIkqIsmCmvhWsUKihWhd4L5GCRW3ovGZVBQRLfovGh1IJeDRmh/d/Droqx8gmvefqN4+e6KxOsxjPoEic6Qo6p+1wp39cWrQKWhDt1W6dwKl2YLWYKejqZsctDXMP3hV5+hEtoxW5bWEvL//ZElgYm31qB4t/n0je69qzifSI1taXBaUOheCfbeD+yKkEJsh+WELM+X1lVh/UA2+cYDaR8SzxXLMoZOJnpHP7ey/kTfgrUgWxMP74L7tnvgehkOxdsd7RX0Ov6MvFqtbKp0GYf2JuC8wmAq4HBGXfSXTqkVFMxjGKi8rv+llVBmrYsZHQ7JjMcY0KzNfy5PJmvy+6/LoBa6ocsxXWMtV4ifshjfjL1IvIcU8g/twq0I212+kU="
      - secure: "PLnaz4I8COZSyMv6HLjBlNiGnB+EZVxhqM6P9efDVQ5yikQWGCEZO+xKnrnz4o2uqJigzq1VMYFmGyFE9POV/YTf9Ze/RUxe7ESADMxvUNNNcmpxAAT6bPmYsHrSdroikXN/bpmxQm0uuHDiz5KbINVw0q7vxEyysrnFkVneJb+px0g1j4FfUIhNDW8FAaks1D8FHsGPC7wABUTTbRIlT9lFeL+uZ1GvCSupotVEAQzKon1XcGrCKPqA6ME2wMv8c++kg0QKpxoXBkzr+M7FMYICroo9TG/W8Z8Z3duaHpZY+hVJ8uNI0OFpZpWr0O2pbrqfGbN+w/wBroee8nt4ODT1EuDIgRZbe8Nj4FAMh/B38iAdwzTD7fKSFfZYbD7O8A87jI35eN7a3obWdjG9KXSgiCIng7QCNybFlNDWhpeiFBQlAG8FbwBZ2+uivfYFJ3unVlu00NNh6sMAFVi0c9zXADWPkhw8PG4VikillAMUg4LTFHP/cOPma1HttcEDOxl7ezR4tA0yI0exaz82qxZQ1C3B0ZIif9nbIfOpVxgzaUNrd6Kx5Jl19imefGJEL17uG9KAZxHRijAQHWjj8n4M2XwpdG8i+d+rRgRoCwo45WxLXAi2h8lNwQJNhTRq7txkdEFj54rY0QCnbq1QlUtkzIZ3iCP/AVEbq3g2mEo="

before_install:
    - echo $MATERIAL2_SCREENSHOT_FIREBASE_KEY
    - echo $MATERIAL2
    - echo $SAUCE_ACCESS_KEY
    - echo $THIRDPARTY_SHARED_SECRET
    - export | grep MATERIAL
matrix:
  fast_finish: true

install:
  - npm install

before_script:
  - mkdir -p $LOGS_DIR

script:
  - ./scripts/ci/build-and-test.sh

cache:
  directories:
    - node_modules
    - $HOME/.pub-cache
    
#addons:
#  jwt:
#    secure: "funKN05yYxLgZNCHX+rduZ4jUcNjLXmHejfNFEKkoxrc1JXC0DIupaz8X/7IUUBxFbJsqQVI7T812jWgI4+003s8hxcgy263Fs/ieh3VLWRCYAkyMautkUyidm+1ZDJWhEPU/7heCQxFKs8AY40tN+oYfb7qor+pceCKqrZ0wiXML+gJ/NrOogaJCydPC79jRJojlVOfqNc+V2caZBtzvwkR85tZO3UQGAhoeHpa9JB2Z2hrMSaTIIphuw4wR9FAR79HtSc6OOkEFGJ0n41Tw1JfnRKdZ6n/QRcYs0NI1mELA6GNNtB2Xp2LNw+8B8xXELKkIIxkZmmMEAbM+EniWwNPljuIaMBmiIPlD3/Ig7sf/BRnUs6/cTNMStal2WnG9h7xhziFWv2jEBh6TJF+uAQ1/BGL4ByxI37iJSwk4Ph32/YnefcY+Ppx/JqoWqGnt8YUMce1ZqlSOrDfP+U5XJTBfRdonUOig8OGVcZFFnNC0ch8mVV5aYoYGkW5UIxYV3ZP38vmR7Vzw0j7H7+eOenpUkopGh74sH0k18M/FIpWdaTFjQgCYFnbR4APol2VQ8YhSLX09s/F0E9w6wNt747KEVQonQF8/pjqmCKfPrvqqH5Xiq1SuCk6O/URzxJ6eKc1Vo2mmQh8fpTTXhnC8VUjSWPilscGEGty1b2ghYk="
